// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsAutoComplete")>]
[<assembly: AssemblyProductAttribute("FsAutoComplete")>]
[<assembly: AssemblyDescriptionAttribute("A command line tool for interfacing with FSharp.Compiler.Service over a pipe.")>]
[<assembly: AssemblyVersionAttribute("0.34.0")>]
[<assembly: AssemblyFileVersionAttribute("0.34.0")>]
[<assembly: AssemblyMetadataAttribute("githash","439f786b27c2d5fc9f6f956f8097b5cd76e4224f")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsAutoComplete"
    let [<Literal>] AssemblyProduct = "FsAutoComplete"
    let [<Literal>] AssemblyDescription = "A command line tool for interfacing with FSharp.Compiler.Service over a pipe."
    let [<Literal>] AssemblyVersion = "0.34.0"
    let [<Literal>] AssemblyFileVersion = "0.34.0"
    let [<Literal>] AssemblyMetadata_githash = "439f786b27c2d5fc9f6f956f8097b5cd76e4224f"
